import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/lib/globals.css";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import { ConvexClientProvider } from "@/components/auth/convex-client-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ConvexAuthNextjsServerProvider>
        <ConvexClientProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased h-dvh bg-white`}
          >
            {children}
          </body>
        </ConvexClientProvider>
      </ConvexAuthNextjsServerProvider>
    </html>
  );
}
